BusinesssTrinitySP01/Models/Job.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace BusinesssTrinitySP01.Models
{
    public class Job
    {
        [Key]
        public int JobID { get; set; }

        [Required]
        [DisplayName("Job Name")]
        public string JobType { get; set; }

        [Required]
        [DisplayName("Job Code")]
        public string JobCode { get; set; }

        [Required]
        [DisplayName("Description")]
        public string JobDescription { get; set; }

        [Required]
        [DisplayName("Requirements")]
        public string JobRequirments { get; set; }

        [Required]
        [DisplayName("Closing Date")]
        [DataType(DataType.Date)]
        public DateTime ClosingDate { get; set; }

        [Required]
        [DisplayName("Post Date")]
        [DataType(DataType.Date)]
        public DateTime DateCreated { get; set; }
    }

    public class Applicant
    {
        [Key]
        public int AppID { get; set; }

        [Required]
        [DisplayName("ID No.")]
        public string RSAID { get; set; }

        [Required]
        [DisplayName("Full Names")]
        public string FName { get; set; }

        [Required]
        [DisplayName("Surname")]
        public string Lastname { get; set; }

        [Required]
        [DisplayName("Phone")]
        public string Phone { get; set; }

        [Required]
        [DisplayName("Email Address")]
        public string Email { get; set; }
    }


    public class JobApplications
    {
        [Key]
        public int JobAppID { get; set; }

        public int JobID { get; set; }

        public int AppID { get; set; }

        [Required]
        [DisplayName("Date Applied")]
        [DataType(DataType.Date)]
        public DateTime AppliedDate { get; set; }

        [Required]
        [DisplayName("Status")]
        public string Status { get; set; }

        [Required]
        [DisplayName("Resume")]
        public byte[] Resume { get; set; }

        public virtual Applicant Applicant { get; set; }
        public virtual Job Job { get; set; }

        [NotMapped]
        public ICollection<Job> jobs { get; set; }

        [NotMapped]
        [DisplayName("RSA ID")]
        public string ID { get; set; }
    }
}

BusinesssTrinitySP01/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BusinesssTrinitySP01.Models;

namespace BusinesssTrinitySP01.Controllers
{
    public class JobsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Jobs
        public ActionResult Index()
        {
            return View(db.jobs.ToList());
        }

        // GET: Jobs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // GET: Jobs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Jobs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "JobID,JobType,JobCode,JobDescription,JobRequirments,ClosingDate,DateCreated")] Job job)
        {
            if (ModelState.IsValid)
            {
                job.DateCreated = DateTime.Now;
                db.jobs.Add(job);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(job);
        }

        // GET: Jobs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // POST: Jobs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "JobID,JobType,JobCode,JobDescription,JobRequirments,ClosingDate,DateCreated")] Job job)
        {
            if (ModelState.IsValid)
            {
                db.Entry(job).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(job);
        }

        // GET: Jobs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        // POST: Jobs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Job job = db.jobs.Find(id);
            db.jobs.Remove(job);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BusinesssTrinitySP01/Views/Jobs/Create.cshtml
@model BusinesssTrinitySP01.Models.Job

@{
    ViewBag.Title = "Post Job";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="jumbotron">
    <div class="container" style="margin-top:4vh;">
        <h3 class="text-center"><b>New Job</b></h3>
        <br />

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.JobCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JobCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobCode, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.JobType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JobType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobType, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.JobDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.JobDescription, new { htmlAttributes = new { @class = "form-control"} })
                @Html.ValidationMessageFor(model => model.JobDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JobRequirments, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.JobRequirments, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobRequirments, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClosingDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClosingDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClosingDate, "", new { @class = "text-danger" })
            </div>
        </div>

     

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Post Job" class="btn btn-primary" />
            </div>
        </div>
    </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>

    </div>
</div>

BusinesssTrinitySP01/Views/Jobs/Delete.cshtml
@model BusinesssTrinitySP01.Models.Job

@{
    ViewBag.Title = "Remove Post";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="jumbotron">
    <div class="container" style="margin-top:4vh;">
        <h3 class="text-center"><b>Remove Job Post</b></h3>
        <br />

      

        <h3>Are you sure you want to remove this post?</h3>
        <div>
            <h4>Job</h4>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.JobType)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.JobType)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.JobCode)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.JobCode)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.JobDescription)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.JobDescription)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.JobRequirments)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.JobRequirments)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ClosingDate)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ClosingDate)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DateCreated)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DateCreated)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-primary" /> |
                    @Html.ActionLink("Back to List", "Index")
                </div>
            }
        </div>

    </div>
</div>

 

BusinesssTrinitySP01/Views/Jobs/Details.cshtml
@model BusinesssTrinitySP01.Models.Job

@{
    ViewBag.Title = "Job Details";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}



<div class="jumbotron">
    <div class="container" style="margin-top:4vh;">
        <h3 class="text-center"><b>Job Details</b></h3>
        <br />


        <div>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.JobType)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.JobType)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.JobCode)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.JobCode)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.JobDescription)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.JobDescription)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.JobRequirments)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.JobRequirments)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.ClosingDate)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.ClosingDate)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DateCreated)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DateCreated)
                </dd>

            </dl>
        </div>

        @if (User.IsInRole("Super Admin"))
        {
            <p>
                @Html.ActionLink("Update", "Edit", new { id = Model.JobID }) |
                @Html.ActionLink("Back to List", "Index")
            </p>
        }



    </div>
</div>

BusinesssTrinitySP01/Views/Jobs/Edit.cshtml
@model BusinesssTrinitySP01.Models.Job

@{
    ViewBag.Title = "Update Post";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}


<div class="jumbotron">
    <div class="container" style="margin-top:4vh;">
        <h3 class="text-center"><b>Update Job</b></h3>
        <br />

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Job</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.JobID)

                <div class="form-group">
                    @Html.LabelFor(model => model.JobType, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.JobType, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.JobType, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.JobCode, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.JobCode, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.JobCode, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.JobDescription, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.JobDescription, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.JobDescription, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.JobRequirments, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.JobRequirments, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.JobRequirments, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ClosingDate, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ClosingDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ClosingDate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DateCreated, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DateCreated, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DateCreated, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>


    </div>
</div>

BusinesssTrinitySP01/Views/Jobs/Index.cshtml
@model IEnumerable<BusinesssTrinitySP01.Models.Job>

@{
    ViewBag.Title = "Vacancies";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}


<div class="jumbotron">
    <div class="container" style="margin-top:4vh;">
        <h3 class="text-center"><b>Jobs</b></h3>
        <br />
        <p>
            @Html.ActionLink("New Job", "Create")
        </p>
        <table class="table table-hover table-bordered">
            @*<tr class="table-active table-bordered">
                <th colspan="4" class="text-center"><h5><b style="font-size:18px;">Requests for quotation</b></h5></th>
            </tr>*@
            <tr class="table">
                <th>
                    @Html.DisplayNameFor(model => model.JobType)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.JobCode)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DateCreated)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ClosingDate)
                </th>

                <th class="text-center">Action</th>
            </tr>
            @foreach (var item in Model)
            {

                <tr>
                    <td>
                        <div class="form-group">
                            <div class="col-md-10">
                                @Html.DisplayFor(modelItem => item.JobType)
                            </div>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            <div class="col-md-10">
                                @Html.DisplayNameFor(model => model.JobCode)
                            </div>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            <div class="col-md-10">
                                @Html.DisplayFor(modelItem => item.DateCreated)
                            </div>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            <div class="col-md-10">
                                @Html.DisplayFor(modelItem => item.ClosingDate)
                            </div>
                        </div>
                    </td>

                    <td class="text-center">
                        <a class="btn btn-primary" href="@Url.Action("Details", "Jobs", new { id = item.JobID })">View Job</a>
                        <a class="btn btn-primary" data-modal="" href="@Url.Action("Edit", "Jobs", new { id = item.JobID })" id="btnCreate">@*<i class="fa fa-eye"></i>*@ Update</a>
                        <a class="btn btn-primary" data-modal="" href="@Url.Action("Delete", "Jobs", new { id = item.JobID })" id="btnCreate">@*<i class="fa fa-eye"></i>*@ Remove</a>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>

@*<div id='myModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'></div>
        </div>
    </div>
</div>
@section scripts{
    @Scripts.Render("~/Scripts/appjs/phones.js")
}*@