BusinesssTrinitySP01/Controllers/RepairItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BusinesssTrinitySP01.Logic;
using BusinesssTrinitySP01.Models;

namespace BusinesssTrinitySP01.Controllers
{
    public class RepairItemsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: RepairItems
        public ActionResult Index()
        {
            var repairItems = db.repairItems.Include(r => r.Equipment);
            return View(repairItems.ToList());
        }

        // GET: RepairItems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RepairItem repairItem = db.repairItems.Find(id);

            var repairItems = db.repairItems.Where(x => x.ItemID == id).Include(x => x.Equipment).FirstOrDefault();

            ViewBag.EName = repairItems.Equipment.Name;

            if (repairItem == null)
            {
                return HttpNotFound();
            }
            return View(repairItem);
        }

        // GET: RepairItems/Create
        public ActionResult Create()
        {
            ViewBag.EquipmentID = new SelectList(db.Equipment, "EquipmentID", "Name");
            return View();
        }

        // POST: RepairItems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ItemID,EquipmentID,Description,img,img2,QouteID")] RepairItem repairItem)
        {
            if (ModelState.IsValid)
            {
                db.repairItems.Add(repairItem);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.EquipmentID = new SelectList(db.Equipment, "EquipmentID", "Name", repairItem.EquipmentID);
            return View(repairItem);
        }

        // GET: RepairItems/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RepairItem repairItem = db.repairItems.Find(id);
            if (repairItem == null)
            {
                return HttpNotFound();
            }
            ViewBag.EquipmentID = new SelectList(db.Equipment, "EquipmentID", "Name", repairItem.EquipmentID);
            return View(repairItem);
        }

        // POST: RepairItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ItemID,ItemCode,EquipmentID,Description,img,img2,RequestID")] RepairItem repairItem)
        {
            if (ModelState.IsValid)
            {
                HttpPostedFileBase file = Request.Files["Img1"];
                HttpPostedFileBase file2 = Request.Files["Bimg"];

                UploadImage service = new UploadImage();
                repairItem.img = service.ConvertToBytes(file);
                repairItem.img2 = service.ConvertToBytes(file2);

                db.Entry(repairItem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EquipmentID = new SelectList(db.Equipment, "EquipmentID", "Name", repairItem.EquipmentID);
            return View(repairItem);
        }

        // GET: RepairItems/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RepairItem repairItem = db.repairItems.Find(id);
            if (repairItem == null)
            {
                return HttpNotFound();
            }
            return View(repairItem);
        }

        // POST: RepairItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RepairItem repairItem = db.repairItems.Find(id);
            db.repairItems.Remove(repairItem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BusinesssTrinitySP01/Views/RepairItems/Create.cshtml
@model BusinesssTrinitySP01.Models.RepairItem

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>RepairItem</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EquipmentID, "EquipmentID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EquipmentID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EquipmentID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.img, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.img, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.img, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.img2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.img2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.img2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RequestID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RequestID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RequestID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BusinesssTrinitySP01/Views/RepairItems/Delete.cshtml
@model BusinesssTrinitySP01.Models.RepairItem

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>RepairItem</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Equipment.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Equipment.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.img)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.img)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.img2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.img2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RequestID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RequestID)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BusinesssTrinitySP01/Views/RepairItems/Details.cshtml
@model BusinesssTrinitySP01.Models.RepairItem

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}


<div class="jumbotron">
    <div class="container">
        <style>
            table {
                width: 100%;
            }

            table, th, td {
                border: 1px solid grey;
                border-collapse: collapse;
                padding: 7px;
            }

                table tr:nth-child(odd) {
                    background-color: #f1f1f1;
                }

                table tr:nth-child(even) {
                    background-color: #ffffff;
                }
        </style>
        <table>
            <tr><td colspan="2" style="width:100%;height:50px; text-align:center;"><b>Items To Repair</b></td></tr>
            <tr>
                <td>
                    <label><b>Item Name:</b>&nbsp;</label>
                    @ViewBag.EName
                </td>
                <td>
                    <label><b>Item Picture:</b>&nbsp;</label>
                    @if (Model.img != null)
                    {
                        var base64 = Convert.ToBase64String(Model.img);
                        var imgsrc = string.Format("data:image/jpg;base64,{0}", base64);
                        <img src='@imgsrc' style="max-width:170px;max-height:200px" />
                    }
                </td>
            </tr>
            <tr>
                <td>
                    <label><b>Repair ID:</b>&nbsp;</label>@Model.RequestID
                </td>
                <td>
                    <label><b>Item Picture:</b>&nbsp;</label>
                    @if (Model.img2 != null)
                    {
                        var base64 = Convert.ToBase64String(Model.img2);
                        var imgsrc = string.Format("data:image/jpg;base64,{0}", base64);
                        <img src='@imgsrc' style="max-width:170px;max-height:200px" />
                    }
                </td>
            </tr>
            <tr>
                <td>
                    <label><b>Equipment ID:</b>&nbsp;</label>@Model.EquipmentID
                </td>
                <td style="width:10px;height:10px">
                    <label><b>Damage Description:</b>&nbsp;</label> @Model.Description
                </td>
            </tr>
        </table>
        <p class="text-center" style="margin-top:5vh;">
            @Html.ActionLink("Back", "Edit","RepairItems", new { id = Model.ItemID }, new {@class="btn btn-success" }) 
        </p>
    </div>
</div>

BusinesssTrinitySP01/Views/RepairItems/Edit.cshtml
@model BusinesssTrinitySP01.Models.RepairItem

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

@using (Html.BeginForm("Edit", "RepairItems", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="jumbotron">
        <div class="container" style="margin-top:2vh;">
            <h2 class="text-center">Upload Picture of Damaged Item(s)</h2>
            <br />
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.ItemID)
            <br />
            <table class="table table-hover">
                <tr class="table-active">
                    <th hidden="hidden">
                        @Html.LabelFor(model => model.EquipmentID, "EquipmentID", htmlAttributes: new { @class = "control-label col-md-2" })
                    </th>
                    <th>
                        @Html.LabelFor(model => model.Equipment.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    </th>
                    <th>
                        @Html.LabelFor(model => model.ItemCode, htmlAttributes: new { @class = "control-label col-md-2" })
                    </th>
                    <th>
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    </th>

                    <th>
                        @Html.LabelFor(model => model.img, new { @class = "control-label col-md-2" })
                    </th>

                    <th>
                        @Html.LabelFor(model => model.img2, new { @class = "control-label col-md-2" })
                    </th>
                    <th>
                        @Html.HiddenFor(model => model.RequestID, htmlAttributes: new { @class = "control-label col-md-2" })
                    </th>
                </tr>

                <tr>
                    <td hidden="hidden">
                        @Html.DropDownList("EquipmentID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.EquipmentID, "", new { @class = "text-danger" })
                    </td>

                    <td>
                        @Html.EditorFor(model => model.Equipment.Name, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    </td>
                    <td>
                        @Html.EditorFor(model => model.ItemCode, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    </td>
                    <td>
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </td>

                    <td>
                        <input type="file" name="Img1" id="Img1" onchange="readURL(this);" class="form-control" required="required" />
                        @Html.ValidationMessageFor(model => model.img)
                    </td>

                    <td>
                        <input type="file" name="Bimg" id="Bimg" onchange="readURL(this);" class="form-control" required="required" />
                        @Html.ValidationMessageFor(model => model.img2)
                    </td>
                    <td>
                        @Html.HiddenFor(model => model.RequestID, new { htmlAttributes = new { @class = "form-control" } })
                    </td>
                </tr>
            </table>
            <div class="form-group">
                <div class="text-center">
                    <input type="submit" value="Save" class="btn btn-success" />
                </div>
            </div>
        </div>
    </div>
}

BusinesssTrinitySP01/Views/RepairItems/Index.cshtml
@model IEnumerable<BusinesssTrinitySP01.Models.RepairItem>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<style>
    .upload:hover, .details:hover {
        color: white;
    }
    .upload {
        font-size: 14px;
        border-radius: 5px;
        background-color: #66b0ff;
        border: none;
        color: white;
        padding: 8px 17px 10px;
        margin-right: 1vw;
        text-align: center;
        text-decoration: none;
    }
    .details {
        font-size: 14px;
        border-radius: 5px;
        background-color: #5cb85c;
        border: none;
        color: white;
        padding: 8px 17px 10px;
        margin-right: 1vw;
        text-align: center;
        text-decoration: none;
    }
</style>

<div class="jumbotron">
    <div class="container" style="margin-top:5vh;">
        <h4 class="text-center"><u>Damaged Items</u></h4>
        <br />
        <table class="table table-hover">
            <tr class="table-active">
                <th>
                    @Html.DisplayNameFor(model => model.RequestID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ItemCode)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th class="text-center"><b>Actions</b></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.RequestID)
                    </td>

                    <th>
                        @Html.DisplayFor(modelItem => item.ItemCode)
                    </th>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>


                    <td class="text-center">
                        @Html.ActionLink("Upload Picture", "Edit", new { id = item.ItemID }, new { @class = "upload" })
                        @Html.ActionLink("Details", "Details", new { id = item.ItemID }, new { @class = "details" })
                    </td>
                </tr>
            }
        </table>
    </div>
</div>