BusinesssTrinitySP01/Models/DecorRental.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace BusinesssTrinitySP01.Models
{
    public class DecorRental
    {

    }
    public class Theme
    {
        [Key]
        public int ThemeId { get; set; }

        [Required]
        [DisplayName("Theme")]
        public string Name { get; set; }

        [Required]
        [DisplayName("Description")]
        public string Description { get; set; }

        [DisplayName("Theme Image")]
        public byte[] Image { get; set; }
    }

    public class Color
    {
        [Key]
        public int BoxId { get; set; }

        [Required]
        [DisplayName("Name")]
        public string Name { get; set; }

        [DisplayName("Color Image")]
        public byte[] Image { get; set; }

        [NotMapped]
        public int qty { get; set; }
    }

    public class DesignComp
    {
        [Key]
        public int CompId { get; set; }

        [ForeignKey("Theme")]
        public int ThemeId { get; set; }

        [Required]
        [DisplayName("Name")]
        public string Name { get; set; }

        [Required]
        [DisplayName("Category")]
        public string Type { get; set; }


        [DisplayName("Component Image")]
        public byte[] Image { get; set; }

        [Required]
        [DisplayName("Quantity")]
        public int Qty { get; set; }

        [Required]
        [DisplayName("Unit Price")]
        [DataType(DataType.Currency)]
        public double UnitPrice { get; set; }

        [Required]
        [DisplayName("Rent Price")]
        [DataType(DataType.Currency)]
        public double RentPrice { get; set; }

        public virtual Theme Theme { get; set; }

    }

    public class CompColor
    {
        [Key]
        public int ColorId { get; set; }

        public int CompId { get; set; }

        public int BoxId { get; set; }

        [NotMapped]
        public bool Select { get; set; }

        [Required]
        [DisplayName("Quantity")]
        public int Qty { get; set; }

        [NotMapped]
        public List<Color> colors { get; set; }

        public virtual DesignComp DesignComp { get; set; }
        public virtual Color Color { get; set; }

    }

    public class Package
    {
        [Key]
        public int PckId { get; set; }

        [Required]
        [DisplayName("Name")]
        public string Name { get; set; }

        [Required]
        [DisplayName("Date")]
        public DateTime DateCreated { get; set; }

        public string CartID { get; set; }

        //[Required]
        public int ThemeID { get; set; }

        public int OrderID { get; set; }

        [ForeignKey("ClientProfile")]
        public string Email { get; set; }

        public virtual ClientProfile ClientProfile { get; set; }

        [NotMapped]
        public IEnumerable<Theme> themes { get; set; }

    }

    public class PackageItem
    {
        [Key]
        public int ItemId { get; set; }

        public int PckId { get; set; }


        public int CompId { get; set; }

        public int BoxId { get; set; }

        [NotMapped]
        public IEnumerable<CompColor> compColors { get; set; }

        [Required]
        [DisplayName("Quantity")]
        public int Qty { get; set; }

        [Required]
        [DisplayName("Price")]
        public double Price { get; set; }

        public virtual Package Package { get; set; }
        public virtual DesignComp DesignComp { get; set; }
        public virtual Color Color { get; set; }
    }
}

BusinesssTrinitySP01/Controllers/DecorRentalsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BusinesssTrinitySP01.Logic;
using BusinesssTrinitySP01.Models;

namespace BusinesssTrinitySP01.Controllers
{
    public class DecorRentalsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private Client_Logic obj = new Client_Logic();
        public string shoppingCartID { get; set; }

        public ActionResult AddPackage(int id)
        {
            ViewBag.oID = id;
            return View();
        }


        // GET: DecorRentals
        public ActionResult GetOrder(int PckID)
        {
            //Session["PckID"] = PckID;
            var userOrders = db.orders.Where(x => x.Email == User.Identity.Name).ToList();

            return View(userOrders);
        }


        public ActionResult SelectedOrder(int PckID)
        {
            Session["PckID"] = PckID;
            //int pckid = Convert.ToInt32(Session["PckID"]);
            //var GetPackage = db.packages.Where(x => x.PckId == pckid).FirstOrDefault();

            //GetPackage.OrderID = oID;
            //db.SaveChanges();

            return RedirectToAction("GetTheme");
        }

        public ActionResult GetTheme()
        {
            var AllThemes = db.themes.ToList();
            return View(AllThemes);
        }

        public ActionResult SelectedTheme(int thmId)
        {
            int PckID = Convert.ToInt32(Session["PckID"]);
            var package = db.packages.Where(x => x.PckId == PckID).FirstOrDefault();

            package.ThemeID = thmId;
            db.SaveChanges();

            return RedirectToAction("GetComponents", new { thmId });
        }

        public ActionResult GetComponents(int thmId)
        {
            Session["theme"] = thmId;
            var designComps = db.designComps.Where(x => x.ThemeId == thmId).ToList();

            //Passes PckID to PackageReview from GetComponents View
            ViewBag.PckID = Convert.ToInt32(Session["PckID"]);
            return View(designComps);
        }

        [HttpGet]
        public ActionResult GetItem(int CompID)
        {
            int PckID = Convert.ToInt32(Session["PckID"]);

            PackageItem packageItem = new PackageItem();

            var component = db.designComps.Where(x => x.CompId == CompID).FirstOrDefault();
            var getColors = db.compColors.Where(x => x.CompId == CompID).ToList();

            var order = db.packages.Where(x => x.PckId == PckID).Select(x => x.OrderID).FirstOrDefault();
            var OItems = db.OrderItems.Where(x => x.OrderID == order).Where(x => x.Equipment.Category.CategoryName == "Chairs" || x.Equipment.Category.CategoryName == "Tables").ToList();

            if (OItems.Count() != 0)
            {
                //Set DesignComps Category to display quantity only if filter is for Chairs and/or Tables Only!!!
                var quantity = OItems.Select(x => x.quantity).FirstOrDefault();
                packageItem.Qty = quantity;
            }
            else
            {
                packageItem.Qty = 1;
            }

            packageItem.compColors = getColors;
            packageItem.CompId = CompID;
            packageItem.PckId = PckID;
            packageItem.Price = component.RentPrice;

            return PartialView(packageItem);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult GetItem(PackageItem packageItem, int comp)
        {
            int thmId = Convert.ToInt32(Session["theme"]);

            if (ModelState.IsValid)
            {
                db.packageItems.Add(packageItem);
                db.SaveChanges();
                return RedirectToAction("GetComponents", new { thmId });
            }
            return RedirectToAction("GetComponents", new { thmId });
        }

        public ActionResult PackageReview(int PckID)
        {
            var packageItems = db.packageItems.Where(x => x.PckId == PckID).Include(x => x.Package).ToList();

            foreach (var item in packageItems)
            {
                item.Price = (item.Price * item.Qty);
            }

            ViewBag.thmID = Convert.ToInt32(Session["theme"]);
            ViewBag.PckID = PckID;

            ViewBag.TotalCost = obj.GetPackageTotal(PckID).ToString("C");
            //ViewBag.TotalCost = packageItems.Select(x => x.Price).Sum().ToString("C");
            ViewBag.Package = packageItems.Select(x => x.Package.Name).FirstOrDefault();


            return View(packageItems);
        }

        public ActionResult AddToCart(int PckID)
        {
            var package = db.packages.Find(PckID);
            package.CartID = obj.GetCartID();
            Session["CartID"] = package.CartID;
            
            db.SaveChanges();

            return RedirectToAction("ViewCart", "Home", new { PckID });
        }

        public ActionResult ViewCart(int PckID)
        {
            string CartID = Convert.ToString(Session["CartID"]);
            var package = db.packages.Where(x => x.CartID == CartID).FirstOrDefault();

            ViewBag.Theme = db.themes.Where(x => x.ThemeId == package.ThemeID).Select(x => x.Name).FirstOrDefault();
            ViewBag.NumItems = db.packageItems.Where(x => x.Package.PckId == PckID).ToList().Count();
            ViewBag.TotalCost = obj.GetPackageTotal(PckID).ToString("C");

            return PartialView(package);
        }

        public ActionResult RemovePackage()
        {
            return RedirectToAction("ViewCart", "Home");
        }

        [HttpGet]
        public ActionResult EditItems(int itmID)
        {
            var pckItem = db.packageItems.Find(itmID);
            var getColors = db.compColors.Where(x => x.CompId == pckItem.CompId).ToList();

            if (pckItem == null)
            {
                return HttpNotFound();
            }
            pckItem.compColors = getColors;

            return PartialView("EditItems", pckItem);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditItems(PackageItem packageItem)
        {
            if (ModelState.IsValid)
            {
                db.Entry(packageItem).State = EntityState.Modified;
                db.SaveChanges();
            }

            return RedirectToAction("PackageReview", new { PckID = packageItem.PckId });
        }

        public ActionResult RemoveItem(int itmID)
        {
            var pckItem = db.packageItems.Find(itmID);

            if (pckItem == null)
            {
                return HttpNotFound();
            }

            return PartialView("RemoveItem", pckItem);
        }

        [HttpPost, ActionName("RemoveItem")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int itmID)
        {
            var pckItem = db.packageItems.Find(itmID);
            db.packageItems.Remove(pckItem);
            db.SaveChanges();

            return RedirectToAction("PackageReview", new { PckID = pckItem.PckId });
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

BusinesssTrinitySP01/Views/DecorRentals/AddPackage.cshtml
@{
    ViewBag.Title = "AddPackage";
}

<div class="jumbotron">
    <div class="container" style="margin-top:8vh;">
        <h4 class="text-success"><b>Would you like to add a custom decoration design?</b></h4>
        <br />

        <table>
            <tr>
                <td>
                    <a class="btn btn-primary" data-modal="" href="@Url.Action("Create", "Packages", new { id = ViewBag.oID })" id="btnCreate">YES</a>
                </td>
                <td></td>
                <td></td>
                <td>
                    <a class="btn btn-secondary" href="@Url.Action("PaymentOption", "Home", new { id = ViewBag.oID })">NO</a>
                </td>
            </tr>
        </table>
      

     
        <!-- modal placeholder-->
        <div id='myModal' class='modal fade in'>
            <div class="modal-dialog">
                <div class="modal-content">
                    <div id='myModalContent'></div>
                </div>
            </div>
        </div>
        @section scripts{
            @Scripts.Render("~/Scripts/appjs/phones.js")
        }

    </div>
</div>

BusinesssTrinitySP01/Views/DecorRentals/EditItems.cshtml
@model BusinesssTrinitySP01.Models.PackageItem

<div class="modal-header">
    <h4 class="modal-title fa fa-edit"> Edit Details</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><i class="fa fa-times-circle"></i></span>
    </button>
</div>
@using (Html.BeginForm("EditItems", "DecorRentals", new { comp = Model.CompId }, FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <div class="modal-body">
            <div class="form-horizontal">
                @Html.HiddenFor(x=>x.ItemId)
                <div class="form-group" hidden>
                    @Html.LabelFor(model => model.PckId, "Package ID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.PckId, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PckId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group" hidden>
                    @Html.LabelFor(model => model.CompId, "Component ID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CompId, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CompId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <table class="table table-bordered">
                    <tr>
                        <th>Color</th>
                        @foreach (var Item in Model.compColors)
                        {
                            <td>
                                <img src="/Colors/RetrieveImage/@Item.BoxId" alt="" height=40 width=40 />
                                <input type="radio" name="BoxId" value="@Item.BoxId" required />
                            </td>
                        }
                    </tr>
                    <tr>
                        <th>Quantity</th>
                        @*<td colspan="5">
                                @Html.EditorFor(model => model.Qty, new { htmlAttributes = new { @class = "form-control" } })
                            </td>*@
                        <td colspan="5">
                            <div class="text-center form-control">
                                <input class="btn btn-secondary" style="padding-bottom:5vh; min-width: 3vw; height: 5vh;" type="button" onclick="decrementValue()" value="-" />
                                <input style="min-inline-size:3vw; line-height:5vh;" class="text-center" type="text" name="Qty" value="@Model.Qty" maxlength="3" size="1" id="quantity" />
                                <input class="btn btn-secondary" style="padding-bottom:5vh; min-width:3vw; height:5vh;" type="button" onclick="incrementValue()" value="+" />
                            </div>
                        </td>
                    </tr>
                </table>

                <div class="form-group">
                    <div class="text-center">
                        @Html.ValidationMessageFor(model => model.Qty, "", new { @class = "text-danger" })
                        @Html.ValidationMessageFor(model => model.BoxId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group" hidden>
                    <label class="control-label col-md-2">Price&nbsp;(<b>R</b>)</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <span id="progress" class="text-center" style="display: none;">
                    <img src="/images/wait.gif" alt="wiat" />
                    Updating...
                </span>
                <input type="submit" value="Update" class="button btn" style="width:50%;" />
                <button class="btn btn-secondary" data-dismiss="modal">CLOSE</button>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    function incrementValue() {
        var value = parseInt(document.getElementById('quantity').value, 10);
        value = isNaN(value) ? 0 : value;
        if (value < 500) {
            value++;
            document.getElementById('quantity').value = value;
        }
    }
    function decrementValue() {
        var value = parseInt(document.getElementById('quantity').value, 10);
        value = isNaN(value) ? 0 : value;
        if (value > 1) {
            value--;
            document.getElementById('quantity').value = value;
        }

    }
</script>

@Scripts.Render("~/bundles/jquery", "~/bundles/jqueryval", "~/Scripts/js/bootstrap.js")

BusinesssTrinitySP01/Views/DecorRentals/GetComponents.cshtml
@model IEnumerable<BusinesssTrinitySP01.Models.DesignComp>

@{
    ViewBag.Title = "Decor Components";
    //Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="~/Content/Admin/GetComps.css" type="text/css"/>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js"></script>
    <!-- Boxicons CDN Link -->
    <script src="https://unpkg.com/boxicons@2.0.9/dist/boxicons.js"></script>
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <div class="sidebar">
        <div class="logo-details">
            <i><box-icon type='solid' name="dashboard" color="white"></box-icon></i>
            <span class="logo_name">Category</span>
        </div>
        <ul class="nav-links">
            <li>
                <a href="#" class="active">
                    <i><box-icon name="abacus" color="white"></box-icon></i>
                    <span class="links_name">All Mixed</span>
                </a>
            </li>
            <li>
                <a href="#">
                    <i><box-icon type='solid' name="inbox" color="white"></box-icon></i>
                    <span class="links_name">Ceiling</span>
                </a>
            </li>
            <li>
                <a href="#">
                    <i><box-icon type='solid' name="wallet" color="white"></box-icon></i>
                    <span class="links_name">Wall</span>
                </a>
            </li>
            <li>
                <a href="#">
                    <i><box-icon name="grid" color="white"></box-icon></i>
                    <span class="links_name">Floor</span>
                </a>
            </li>
            <li>
                <a href="#">
                    <i><box-icon type='solid' name="pie-chart-alt-2" color="white"></box-icon></i>
                    <span class="links_name">Tables</span>
                </a>
            </li>
            <li>
                <a href="#">
                    <i><box-icon color="white" name='chair'></box-icon></i>
                    <span class="links_name">Chairs</span>
                </a>
            </li>
            <li>
                <a href="#">
                    <i><box-icon type='solid' color="white" name='star'></box-icon></i>
                    <span class="links_name">Extras</span>
                </a>
            </li>
        </ul>
    </div>
    <section class="home-section">
        <nav>
            <div class="sidebar-button">
                <i class='bx bx-menu sidebarBtn'></i>
                <span class="dashboard">Design</span>
            </div>
            @using (Html.BeginForm("", "", FormMethod.Get))
            {
                <div class="sorting">
                    <div class="search-box">
                        <input class="bx bx-search" type="submit" value="Change" />
                        <div class="profile-details">
                            <select id="searchDrop" name="searchDrop" class="DropStatus">
                                <option>Change Theme</option>
                                <option>Wedding</option>
                                <option>Party</option>
                                <option>Tradition</option>
                                <option>Funeral</option>
                            </select>
                        </div>
                    </div>
                </div>
            }
        </nav>
        <div class="home-content">
            <div class="overview-boxes">
                @foreach (var item in Model)
                {
                    <div style="margin-bottom:3vh;" class="box" id="design">
                        <div class="men-thumb-item text-center">
                            @if (item.Image != null)
                            {
                                var base64 = Convert.ToBase64String(item.Image);
                                var imgsrc = string.Format("data:image/jpg;base64,{0}", base64);
                                <img src="@imgsrc" alt="" height=180 width=220 />
                            }
                            <div class="men-cart-pro">
                                <div class="inner-men-cart-pro">
                                    <div class="inner-men-cart-pro">
                                        @*<span class="link-product-add-cart btnEdit" id="edit_@item.CompId" onclick="createModal('@Url.Action("GetItems", "DesignComps" , new {Id=item.CompId })')"><i class="fa fa-shopping-cart"></i> Select</span>*@
                                        <a class="link-product-add-cart btnEdit" data-modal="" href="@Url.Action("GetItem", "DecorRentals", new { CompID = item.CompId })" id="btnCreate"><i class="fa fa-shopping-cart"></i> Select</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
        <div class="snipcart-details top_brand_home_details item_add single-item hvr-outline-out">
            <a class="button btn" href="@Url.Action("PackageReview","DecorRentals", new {PckID = ViewBag.PckID })"><i class="fa fa-box"></i> Finalize Package</a>
        </div>
    </section>

    <!-- Package Item Details - Modal -->
    @*<div class="modal fade" id="myModal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="static" data-keyboard="false">
            <div class="modal-dialog">
                <div class="modal-content" id="modelContent">
                </div>
            </div>
        </div>
        <script>
            function createModal(url) {
                $('#modelContent').load(url);
                $('#myModal').modal('show');
            }
        </script>*@

    <!-- modal placeholder-->
    <div id='myModal' class='modal fade in'>
        <div class="modal-dialog">
            <div class="modal-content">
                <div id='myModalContent'></div>
            </div>
        </div>
    </div>
    @section scripts{
        @Scripts.Render("~/Scripts/appjs/phones.js")
    }

    <!-- //Package Item Details - Modal -->

    <script>
        let sidebar = document.querySelector(".sidebar");
        let sidebarBtn = document.querySelector(".sidebarBtn");
        sidebarBtn.onclick = function () {
            sidebar.classList.toggle("active");
            if (sidebar.classList.contains("active")) {
                sidebarBtn.classList.replace("bx-menu", "bx-menu-alt-right");
            } else
                sidebarBtn.classList.replace("bx-menu-alt-right", "bx-menu");
        }
    </script>
    <script type="text/javascript">
        document.getElementById("circle").onclick = function () {

            document.getElementById("rounded").style.display = "none";
        }

        document.getElementById("rounded").onclick = function () {

            document.getElementById("rounded").style.display = "none";

        }

        document.getElementById("square").onclick = function () {

            document.getElementById("square").style.display = "none";
        }
    </script>

</body>

BusinesssTrinitySP01/Views/DecorRentals/GetItem.cshtml
@model BusinesssTrinitySP01.Models.PackageItem

<div class="modal-header">
    <h4 class="modal-title fa fa-edit">Item Details</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><i class="fa fa-times-circle"></i></span>
    </button>
</div>
@using (Html.BeginForm("GetItem", "DecorRentals", new { comp = Model.CompId }, FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <div class="modal-body">
            @Html.Action("ComponentDetails", "DesignComps", new { Id = Model.CompId })
            <div class="form-horizontal">

                <div class="form-group" hidden>
                    @Html.LabelFor(model => model.PckId, "Package ID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.PckId, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PckId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group" hidden>
                    @Html.LabelFor(model => model.CompId, "Component ID", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CompId, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CompId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <table class="table table-bordered">
                    <tr>
                        <th>Color</th>
                        @foreach (var Item in Model.compColors)
                        {
                            <td>
                                <img src="/Colors/RetrieveImage/@Item.BoxId" alt="" height=40 width=40 />
                                <input type="radio" name="BoxId" value="@Item.BoxId" required />
                            </td>
                        }
                    </tr>
                    <tr>
                        <th>Quantity</th>
                        @*<td colspan="5">
                            @Html.EditorFor(model => model.Qty, new { htmlAttributes = new { @class = "form-control" } })
                        </td>*@
                    <td colspan="5">
                        <div class="text-center form-control">
                            <input class="btn btn-secondary" style="min-width: 3vw; height: 5vh;" type="button" onclick="decrementValue()" value="-" />
                            <input style="min-inline-size:3vw; height:4.8vh;" class="text-center" type="text" name="Qty" value="@Model.Qty" maxlength="3" size="1" id="quantity" />
                            <input class="btn btn-secondary" style="min-width:3vw; height:5vh;" type="button" onclick="incrementValue()" value="+" />
                        </div>
                    </td>
                    </tr>
                </table>

                <div class="form-group">
                    <div class="text-center">
                        @Html.ValidationMessageFor(model => model.Qty, "", new { @class = "text-danger" })
                        @Html.ValidationMessageFor(model => model.BoxId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group" hidden>
                    <label class="control-label col-md-2">Price&nbsp;(<b>R</b>)</label>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                        @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                    </div>
                </div>

            </div>
            <div class="modal-footer">
                <span id="progress" class="text-center" style="display: none;">
                    <img src="/images/wait.gif" alt="wiat" />
                    Adding...
                </span>
                <input type="submit" value="Add To Package" class="button btn" style="width:50%;" />
                <button class="btn btn-secondary" data-dismiss="modal">CLOSE</button>
            </div>
        </div>
    </div>
}

<script type="text/javascript">
    function incrementValue() {
        var value = parseInt(document.getElementById('quantity').value, 10);
        value = isNaN(value) ? 0 : value;
        if (value < 500) {
            value++;
            document.getElementById('quantity').value = value;
        }
    }
    function decrementValue() {
        var value = parseInt(document.getElementById('quantity').value, 10);
        value = isNaN(value) ? 0 : value;
        if (value > 1) {
            value--;
            document.getElementById('quantity').value = value;
        }

    }
</script>

@Scripts.Render("~/bundles/jquery", "~/bundles/jqueryval", "~/Scripts/js/bootstrap.js")

BusinesssTrinitySP01/Views/DecorRentals/GetTheme.cshtml
@model IEnumerable<BusinesssTrinitySP01.Models.Theme>

@{
    ViewBag.Title = "Select Theme";
}

<div class="jumbotron">
    <div class="container">
        <h3 class="text-center"><b>Select Decoration Theme</b></h3>
        <br />
        <table class="table table-hover table-bordered">
            <tr class="table">
                <th>Theme Name</th>
                <th>Theme Description</th>
                <th>Theme Image</th>
                <th class="text-center">Action</th>
            </tr>
            @foreach(var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @if (item.Image != null)
                        {
                            var base64 = Convert.ToBase64String(item.Image);
                            var imgsrc = string.Format("data:image/jpg;base64,{0}", base64);
                            <img src='@imgsrc' style="width:120px;height:90px" />
                        }
                    </td>
                    <td class="text-center">
                        <a class="btn btn-primary" href="@Url.Action("SelectedTheme","DecorRentals", new {thmId=item.ThemeId })"><i class="fa fa-mouse-pointer"></i> Select</a>
                    </td>
                </tr>
            }

        </table>
    </div>
</div>