BusinesssTrinitySP01/Controllers/DesignCompsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BusinesssTrinitySP01.Logic;
using BusinesssTrinitySP01.Models;

namespace BusinesssTrinitySP01.Controllers
{
    public class DesignCompsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: DesignComps
        public ActionResult Index()
        {
            var designComps = db.designComps.Include(d => d.Theme);
            return View(designComps.ToList());
        }


        // GET: DesignComps/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DesignComp designComp = db.designComps.Find(id);
            if (designComp == null)
            {
                return HttpNotFound();
            }
            return View(designComp);
        }

        //public ActionResult GetOrder(int PckID)
        //{
        //    Session["PckID"] = PckID;
        //    var userOrders = db.orders.Where(x=>x.Email==User.Identity.Name).ToList();

        //    return View(userOrders);
        //}

        //public ActionResult SelectedOrder(int oID)
        //{
        //    int PckID = Convert.ToInt32(Session["PckID"]);
        //    var GetPackage = db.packages.Where(x => x.PckId == PckID).FirstOrDefault();

        //    GetPackage.OrderID = oID;
        //    db.SaveChanges();

        //    return RedirectToAction("GetTheme");
        //}

        //public ActionResult GetTheme()
        //{
        //    var AllThemes = db.themes.ToList();
        //    return View(AllThemes);
        //}

        //public ActionResult SelectedTheme(int thmId)
        //{
        //    int PckID = Convert.ToInt32(Session["PckID"]);
        //    var package = db.packages.Where(x => x.PckId == PckID).FirstOrDefault();

        //    package.ThemeID = thmId;
        //    db.SaveChanges();

        //    return RedirectToAction("GetComponents", new { thmId });
        //}


        //public ActionResult GetComponents(int thmId)
        //{
        //    Session["theme"] = thmId;
        //    var designComps = db.designComps.Where(x => x.ThemeId == thmId).ToList();

        //    return View(designComps);
        //}

        public ActionResult ComponentDetails(int? Id)
        {
            if (Id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DesignComp designComp = db.designComps.Find(Id);
            if (designComp == null)
            {
                return HttpNotFound();
            }
            return PartialView(designComp);
        }

        //[HttpGet]
        //public ActionResult GetItem(int CompID)
        //{
        //    int PckID = Convert.ToInt32(Session["PckID"]);

        //    PackageItem packageItem = new PackageItem();

        //    var component = db.designComps.Where(x => x.CompId == CompID).FirstOrDefault();
        //    var getColors = db.compColors.Where(x => x.CompId == CompID).ToList();

        //    var order = db.packages.Where(x => x.PckId == PckID).Select(x => x.OrderID).FirstOrDefault();
        //    var OItems = db.OrderItems.Where(x => x.OrderID == order).Where(x=>x.Equipment.Category.CategoryName== "Chairs" || x.Equipment.Category.CategoryName=="Tables").ToList();

        //    if (OItems.Count() != 0) 
        //    {
        //        //Set DesignComps Category to display quantity only if filter is for Chairs and/or Tables Only!!!
        //        var quantity = OItems.Select(x => x.quantity).FirstOrDefault();
        //        packageItem.Qty = quantity;
        //    }
        //    else
        //    {
        //        packageItem.Qty = 1;
        //    }

        //    packageItem.compColors = getColors;
        //    packageItem.CompId = CompID;
        //    packageItem.PckId = PckID;
        //    packageItem.Price = component.RentPrice;

        //    return PartialView(packageItem);
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult GetItem(PackageItem packageItem, int comp)
        //{
        //    int thmId = Convert.ToInt32(Session["theme"]);

        //    if (ModelState.IsValid)
        //    {
        //        db.packageItems.Add(packageItem);
        //        db.SaveChanges();
        //        return RedirectToAction("GetComponents", new { thmId });
        //    }
        //    return RedirectToAction("GetComponents", new { thmId });
        //}

        // GET: DesignComps/Create
        public ActionResult Create()
        {
            ViewBag.ThemeId = new SelectList(db.themes, "ThemeId", "Name");
            return View();
        }

        // POST: DesignComps/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CompId,ThemeId,Name,Type,Image,Qty,UnitPrice,RentPrice")] DesignComp designComp)
        {
            if (ModelState.IsValid)
            {
                HttpPostedFileBase file = Request.Files["DesignImage"];
                UploadImage service = new UploadImage();
                designComp.Image = service.ConvertToBytes(file);
                db.designComps.Add(designComp);
                db.SaveChanges();
                return RedirectToAction("AddColor", "CompColors", new { id = designComp.CompId });
            }

            ViewBag.ThemeId = new SelectList(db.themes, "ThemeId", "Name", designComp.ThemeId);
            return View(designComp);
        }

        public ActionResult AddColor(int? id)
        {
            if (id != null)
            {

            }
            return View();
        }

        // GET: DesignComps/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DesignComp designComp = db.designComps.Find(id);
            if (designComp == null)
            {
                return HttpNotFound();
            }
            ViewBag.ThemeId = new SelectList(db.themes, "ThemeId", "Name", designComp.ThemeId);
            return View(designComp);
        }

        // POST: DesignComps/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CompId,ThemeId,Name,Type,Image,Qty,UnitPrice,RentPrice")] DesignComp designComp)
        {
            if (ModelState.IsValid)
            {
                db.Entry(designComp).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ThemeId = new SelectList(db.themes, "ThemeId", "Name", designComp.ThemeId);
            return View(designComp);
        }

        // GET: DesignComps/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DesignComp designComp = db.designComps.Find(id);
            if (designComp == null)
            {
                return HttpNotFound();
            }
            return View(designComp);
        }

        // POST: DesignComps/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DesignComp designComp = db.designComps.Find(id);
            db.designComps.Remove(designComp);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BusinesssTrinitySP01/Views/DesignComps/ComponentDetails.cshtml
@model BusinesssTrinitySP01.Models.DesignComp

@*<div class="modal-header">
    <h4 class="modal-title">Item Details</h4>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true"><i class="fa fa-times-circle"></i></span>
    </button>
</div>
<div class="modal-body">*@
<div>
    <table class="table table-bordered">
        <tr>
            <td>@Html.DisplayNameFor(model => model.Name)</td>
            <td>@Html.DisplayFor(model => model.Name)</td>
        </tr>
        <tr>
            <td>
                @*@Html.DisplayNameFor(model => model.RentPrice)*@
                <label>Price&nbsp;(<b>R</b>)</label>
            </td>
            <td>@Html.DisplayFor(model => model.RentPrice)</td>
        </tr>
        <tr>
            <td>@Html.DisplayNameFor(model => model.Image)</td>
            <td>
                @if (Model.Image != null)
                {
                    var base64 = Convert.ToBase64String(Model.Image);
                    var imgsrc = string.Format("data:image/jpg;base64,{0}", base64);
                    <img src='@imgsrc' style="width:80px;height:80px" />
                }
            </td>
        </tr>
    </table>
</div>
    @*</div>
</div>
<div class="modal-footer">
    <a style="padding: 0 20px 0;" href="@Url.Action(actionName: "AddToCart", controllerName: "Home", routeValues: new { id = Model.CompId })" data-toggle="modal" , data-target="#exampleModal" class="link-product-add-cart"><i class="fa fa-shopping-cart"></i> Add To Package</a>
    <button type="button" class="btn btn-default"
            data-dismiss="modal">
        Close
    </button>
</div>*@

BusinesssTrinitySP01/Views/DesignComps/Create.cshtml
@model BusinesssTrinitySP01.Models.DesignComp

@{
    ViewBag.Title = "New Design";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="jumbotron">
    <div class="container" style="margin-top:4vh;">
        <br />
        <h2>New Design</h2>

        @using (Html.BeginForm("Create", "DesignComps", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.ThemeId, "Theme", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("ThemeId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ThemeId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(model => model.Type, new List<SelectListItem>
                                                                        {
                                                                          new SelectListItem {Text = "Wall"},
                                                                          new SelectListItem {Text = "Ceiling"},
                                                                          new SelectListItem {Text = "Floor"},
                                                                          new SelectListItem {Text = "Chairs"},
                                                                          new SelectListItem {Text = "Tables"},
                                                                          new SelectListItem {Text = "Extras"}
                                                          }, "--Select--", htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="file" name="DesignImage" id="DesignImage" onchange="readURL(this);" class="form-control" required="required" />
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Qty, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Qty, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Qty, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.UnitPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.UnitPrice, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.UnitPrice, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.RentPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.RentPrice, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.RentPrice, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Add Design" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>


    </div>
</div>

BusinesssTrinitySP01/Views/DesignComps/Delete.cshtml
@model BusinesssTrinitySP01.Models.DesignComp

@{
    ViewBag.Title = "Remove Component";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="jumbotron">
    <div class="container" style="margin-top:4vh;">
        <h3 class="text-center"><b>Design Component</b></h3>
        <br />
        <h3>Are you sure you want to remove this component?</h3>
        <div>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Theme.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Theme.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Type)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Type)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Image)
                </dt>

                <dd>
                    @if (Model.Image != null)
                    {
                        var base64 = Convert.ToBase64String(Model.Image);
                        var imgsrc = string.Format("data:image/jpg;base64,{0}", base64);
                        <img src='@imgsrc' style="max-width:80px;max-height:80px" />
                    }
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Qty)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Qty)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.UnitPrice)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.UnitPrice)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.RentPrice)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.RentPrice)
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Remove" class="btn btn-primary" /> |
                    @Html.ActionLink("Back to List", "Index")
                </div>
            }
            </div>

        </div>
    </div>

BusinesssTrinitySP01/Views/DesignComps/Details.cshtml
@model BusinesssTrinitySP01.Models.DesignComp

@{
    ViewBag.Title = "Design Component";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<div class="jumbotron">
    <div class="container" style="margin-top:4vh;">
        <h3 class="text-center"><b>Design Component</b></h3>
        <br />
        <div>
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Theme.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Theme.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Type)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Type)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Image)
                </dt>

                <dd>
                    @if (Model.Image != null)
                    {
                        var base64 = Convert.ToBase64String(Model.Image);
                        var imgsrc = string.Format("data:image/jpg;base64,{0}", base64);
                        <img src='@imgsrc' style="max-width:80px;max-height:80px" />
                    }
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Qty)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Qty)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.UnitPrice)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.UnitPrice)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.RentPrice)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.RentPrice)
                </dd>

            </dl>
        </div>
        <p>
            @Html.ActionLink("Update Component", "Edit", new { id = Model.CompId }) |
            @Html.ActionLink("Back to List", "Index")
        </p>


    </div>
</div>

    

BusinesssTrinitySP01/Views/DesignComps/Edit.cshtml
@model BusinesssTrinitySP01.Models.DesignComp

@{
    ViewBag.Title = "Update Component";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="jumbotron">
    <div class="container" style="margin-top:4vh;">
        <h3 class="text-center"><b>Update Design Component</b></h3>
        <br />
        @using (Html.BeginForm("Create", "DesignComps", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>DesignComp</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.CompId)

                <div class="form-group">
                    @Html.LabelFor(model => model.ThemeId, "ThemeId", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("ThemeId", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.ThemeId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Type, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="file" name="DesignImage" id="DesignImage" onchange="readURL(this);" class="form-control" required="required" />
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Qty, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Qty, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Qty, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.UnitPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.UnitPrice, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.UnitPrice, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.RentPrice, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.RentPrice, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.RentPrice, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Save" class="btn btn-primary" />
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>

    </div>
</div>

   

BusinesssTrinitySP01/Views/DesignComps/Index.cshtml
@model IEnumerable<BusinesssTrinitySP01.Models.DesignComp>

@{
    ViewBag.Title = "Decor Designs";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<div class="jumbotron">
    <div class="container" style="margin-top:4vh;">
        <h3 class="text-center"><b>Decor Design Components</b></h3>
        <br />
        <p>
            @Html.ActionLink("Add Design Component", "Create", "DesignComps")
        </p>
        <p>
            @Html.ActionLink("Add Theme", "Create", "Themes")
        </p>
        <p>
            @Html.ActionLink("Add Decor Colors", "Create", "Colors")
        </p>

        <table class="table table-hover table-bordered">

            <tr class="table">
                <th>
                    @Html.DisplayNameFor(model => model.Theme.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Type)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Image)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Qty)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UnitPrice)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.RentPrice)
                </th>
                <th class="text-center">Action</th>
            </tr>
            @foreach (var item in Model)
            {

                <tr>

                    <td>
                        <div class="form-group">
                            <div class="col-md-10">
                                @Html.DisplayFor(modelItem => item.Theme.Name)
                            </div>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            <div class="col-md-10">
                                @Html.DisplayFor(modelItem => item.Name)
                            </div>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            <div class="col-md-10">
                                @Html.DisplayFor(modelItem => item.Type)
                            </div>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            <div class="col-md-10">
                                @if (item.Image != null)
                                {
                                    var base64 = Convert.ToBase64String(item.Image);
                                    var imgsrc = string.Format("data:image/jpg;base64,{0}", base64);
                                    <img src='@imgsrc' style="max-width:80px;max-height:80px" />
                                }
                            </div>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            <div class="col-md-10">
                                @Html.DisplayFor(modelItem => item.Qty)
                            </div>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            <div class="col-md-10">
                                @Html.DisplayFor(modelItem => item.UnitPrice)
                            </div>
                        </div>
                    </td>
                    <td>
                        <div class="form-group">
                            <div class="col-md-10">
                                @Html.DisplayFor(modelItem => item.RentPrice)
                            </div>
                        </div>
                    </td>

                    <td class="text-center">
                        @Html.ActionLink("Update", "Edit", new { id = item.CompId }) |
                        @Html.ActionLink("View", "Details", new { id = item.CompId }) |
                        @Html.ActionLink("Remove", "Delete", new { id = item.CompId })
                    </td>
                </tr>
            }
        </table>
    </div>
</div>